name: Converted Workflow
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  Build:
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        os:
          - ubuntu-18.04
        node-version:
          - 14.x
    steps:
      - name: 'Set up Node.js ${{ matrix.node-version }}'
        uses: actions/setup-node@v1
        with:
          node-version: '${{ matrix.node-version }}'
      - uses: actions/checkout@v2
      - run: echo "nothing needs to be installed"
      - run: echo "no tests"
      - run: docker --version
      - run: docker build -t udagram-api-feed ../../udagram-api-feed
      - run: docker build -t udagram-api-user ../../udagram-api-user
      - run: docker build -t udagram-frontend ../../udagram-frontend
      - run: docker build -t udagram-reverseproxy ../../udagram-reverseproxy
      - run: docker tag udagram-api-feed buchilazarus/udagram-api-feed:v1
      - run: docker tag udagram-api-user buchilazarus/udagram-api-user:v1
      - run: docker tag udagram-frontend buchilazarus/udagram-frontend:v1
      - run: docker tag udagram-reverseproxy buchilazarus/udagram-reverseproxy:v1
      - run: >-
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME"
          --password-stdin
      - run: docker push buchilazarus/udagram-api-feed:v1
      - run: docker push buchilazarus/udagram-api-user:v1
      - run: docker push buchilazarus/udagram-frontend:v1
      - run: docker push buchilazarus/udagram-reverseproxy:v1
